[packages]
[packages."Hello World"]
"1.0.0" = "https://alt.innatical.com/repo/package.apkg"
[packages."Hello World 2"]
"1.0.0" = "https://alt.innatical.com/repo/package2.apkg"
"1.0.1" = "https://alt.innatical.com/repo/package3.apkg"
[packages."dependency"]
"1.0.1" = "https://alt.innatical.com/repo/dependency.apkg"
