[packages]
[packages.catalogue]
"1" = "https://alt.innatical.com/repo/linux/amd64/boopbrowser
[packages.applist]
"0.1" = "https://url.temp/repo/linux/amd64/booplinux-core
"0.1" = "https://url.temp/repo/linux/amd64/booplinux-core-dnf
"0.1" = "https://url.temp/repo/linux/amd64/booplinux-extras
"0.1" = "https://url.temp/repo/linux/amd64/booplinux-extras-dnf
